### ISSUE TITLE
Secret name mismatch

### ISSUE THREAD

**Issue by DawidCh** [squareops/terraform-kubernetes-argocd#8]
Hello.
Ingress which is setup by this module references to not existing secret. TLS key and cert are kept in [argocd-secret](https://github.com/argoproj/argo-helm/blob/047ba6b24df9977ec773ca5cf0f00a70565e5c06/charts/argo-cd/templates/argocd-configs/argocd-secret.yaml#L5)
but in default values.yaml in this module reference to argocd-tls:
https://github.com/squareops/terraform-kubernetes-argocd/blob/e4d58ec6b39b8318013116ea94db3345bfd6cc44/helm/values/values.yaml#L97
I know that it is easy to modify that by `argocd_config.values_yaml`:
```yaml
server:
  ingress:
    tls:
      - secretName: argocd-secret
        hosts:
          ${hostname}
```
but then substitution to tls.hosts https://github.com/squareops/terraform-kubernetes-argocd/blob/e4d58ec6b39b8318013116ea94db3345bfd6cc44/helm/values/values.yaml#L99 is not being resolved in provided yaml file.
Is there sth I can use to make it work?
Regards, Dawid.
